name: publish image
permissions: write-all

on:
  push:
    branches:
      - dev
      - main
  release:
    types:
      - created

jobs:
  build:
    name: publish image
    runs-on: ubuntu-latest
    steps:
      - name: set up env
        run: cat versions.env >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: prepare
        id: prepare_tag
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        if: ${{ github.event_name == 'release' }}

      - name: prepare
        id: prepare_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        if: ${{ github.event_name != 'release' }}

      - name: Build and push image - release
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            GH_RUNNER_VERSION
            DOCKER_COMPOSE_VERSION
          tags: |
            ghcr.io/fopina/github-runner:${{ env.GH_RUNNER_VERSION }}
            ghcr.io/fopina/github-runner:${{ steps.prepare_tag.outputs.tag_name }}
            ghcr.io/fopina/github-runner:latest
          context: docker
        if: ${{ github.event_name == 'release' }}
      
      - name: Build and push image - branch
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            GH_RUNNER_VERSION
            DOCKER_COMPOSE_VERSION
          tags: |
            ghcr.io/fopina/github-runner:${{ steps.prepare_branch.outputs.branch_name }}-${{ env.GH_RUNNER_VERSION }}
            ghcr.io/fopina/github-runner:${{ steps.prepare_branch.outputs.branch_name }}
          context: docker
        if: ${{ github.event_name != 'release' }}
