name: publish image
permissions: write-all

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    name: publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: prepare
        id: prepare_branch
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "runner_version=$(cat docker/Dockerfile | grep ^FROM | head -n1 | cut -d ':' -f2)" >> $GITHUB_OUTPUT

      - name: Build and push image - release
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            GH_RUNNER_VERSION
            DOCKER_COMPOSE_VERSION
          tags: |
            ghcr.io/fopina/github-runner:${{ steps.prepare_branch.outputs.runner_version }}
            ghcr.io/fopina/github-runner:latest
          context: docker
        if: ${{ steps.prepare_branch.outputs.branch_name == 'main' }}
      
      - name: Build and push image - branch
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            GH_RUNNER_VERSION
            DOCKER_COMPOSE_VERSION
          tags: |
            ghcr.io/fopina/github-runner:${{ steps.prepare_branch.outputs.branch_name }}-${{ steps.prepare_branch.outputs.runner_version }}
            ghcr.io/fopina/github-runner:${{ steps.prepare_branch.outputs.branch_name }}
          context: docker
        if: ${{ steps.prepare_branch.outputs.branch_name != 'main' }}
