name: publish to dockerhub

on:
  push:
    branches:
      - dev
      - master
      - cleanup
  release:
    types:
      - created

jobs:
  build:
    name: publish to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: login to dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      -
        name: prepare
        id: prepare
        run: |
            TAG=${${GITHUB_REF#refs/tags/}#refs/heads/}
            echo ::set-output name=tag_name::${TAG}

      - name: build image
        run: make build
      
      - name: tag and push
        run:
          make tag TAG=${{ steps.prepare.outputs.tag_name }}
          make push TAG=${{ steps.prepare.outputs.tag_name }}
      
      - name: tag and push latest
        run:
          make tag TAG=latest
          make push TAG=latest
        if: ${{ github.event_name == 'release' }}
